### ISSUE TITLE
Clicking on the logo on top left corner not redirecting to homepage

### ISSUE THREAD

**Issue by DefCon-007** [kossiitkgp/website#19]
Base_url : http://kossiitkgp.in/#about
Url redirected to : http://kossiitkgp.in/index.html
Error :
<img width="1440" alt="screen shot 2016-10-14 at 8 47 32 pm" src="https://cloud.githubusercontent.com/assets/16754547/19392679/741fe4cc-924f-11e6-87a3-2303f84140d8.png">

**Comment by OrkoHunter** [comment]
Fixed in #21
